name: "Build apps/web"
on:
  pull_request:
    branches:
      - master

jobs:
  build-project:
    name: Build apps/web
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true
      CI: true
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build nextjs
        run: bun run build